<a href="https://colab.research.google.com/github/Terrence536/MSSP-6070/blob/main/WeeklyModules/Week06/Week_6_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import userdata
import os

github_token = userdata.get('Git_Key')
owner = 'Terrence536' # Replace with the GitHub repository owner
repository = 'MSSP-6070' # Replace with the GitHub repository name

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

Changed directory to: /content/MSSP-6070

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("WeeklyModules/Week06/Student Performance Data.csv")

In [4]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [5]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'math score', 'reading score', 'writing score', 'total score',
       'test preparation course', 'admission prospect'],
      dtype='object')

In [6]:
add_average = lambda x: x.assign(
    average_score=((x['math score'] + x['reading score'] + x['writing score']) / 3).round(2)
)

In [7]:
new_df = add_average(df)
new_df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,average_score
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium,72.67
1,female,group C,some college,standard,69,90,88,247,completed,high,82.33
2,female,group B,master's degree,standard,90,95,93,278,none,high,92.67
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low,49.33
4,male,group C,some college,standard,76,78,75,229,none,high,76.33

### Lambda function for average score
This lambda function takes the original Student Performance DataFrame as input and returns a new DataFrame with an additional 'average_score' column.