<a href="https://colab.research.google.com/github/Terrence536/MSSP-6070/blob/main/WeeklyModules/Week05/Week_5_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import userdata
import os

github_token = userdata.get('Git_Key')
owner = 'Terrence536' # Replace with the GitHub repository owner
repository = 'MSSP-6070' # Replace with the GitHub repository name

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

Changed directory to: /content/MSSP-6070

In [ ]:
!ls WeeklyModules/Week05

aapl.csv  amzn.csv  fb.csv  goog.csv  nflx.csv

# 2a

In [7]:

%cd WeeklyModules/Week05
!pwd
!ls

[Errno 2] No such file or directory: 'WeeklyModules/Week05'
/content/MSSP-6070/WeeklyModules/Week05
/content/MSSP-6070/WeeklyModules/Week05
aapl.csv  amzn.csv  fb.csv  goog.csv  nflx.csv

In [9]:
import pandas as pd

# 2b

In [10]:
aapl = pd.read_csv("aapl.csv")
amzn = pd.read_csv("amzn.csv")
fb = pd.read_csv("fb.csv")
goog = pd.read_csv("goog.csv")
nflx = pd.read_csv("nflx.csv")

In [11]:
aapl.head()

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

# 2c

In [12]:
aapl["ticker"] = "AAPL"
amzn["ticker"] = "AMZN"
fb["ticker"] = "FB"
goog["ticker"] = "GOOG"
nflx["ticker"] = "NFLX"

In [14]:
aapl.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

# 2d

In [18]:
faanf = pd.concat([fb, aapl, amzn, nflx, goog], ignore_index=True)

In [19]:
faanf.head()

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

In [20]:
faanf.shape

(1255, 7)

# 2e

In [23]:
faanf.to_csv("faanf.csv", index=False)

In [24]:
!ls

aapl.csv  amzn.csv  faanf.csv  faang.csv  fb.csv  goog.csv  nflx.csv

In [25]:
pd.read_csv("faanf.csv").head()

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

# 2f

In [26]:
faanf = pd.read_csv("faanf.csv")

In [27]:
faanf["date"] = pd.to_datetime(faanf["date"])

In [28]:
faanf["volume"] = faanf["volume"].astype(int)

In [29]:
faanf = faanf.sort_values(by=["date", "ticker"])

In [30]:
faanf.head(10)

           date       open       high        low      close    volume ticker
251  2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
502  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
0    2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
1004 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
753  2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX
252  2018-01-03   169.2521   171.2337   168.6929   168.9578  29517899   AAPL
503  2018-01-03  1188.3000  1205.4900  1188.3000  1204.2000   3108793   AMZN
1    2018-01-03   181.8800   184.7800   181.3300   184.6700  16886563     FB
1005 2018-01-03  1064.3100  1086.2900  1063.2100  1082.4800   1430170   GOOG
754  2018-01-03   202.0500   206.2100   201.5000   205.0500   8591369   NFLX

In [31]:
faanf.dtypes

date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
ticker            object
dtype: object

# 2g

In [32]:
faanf.nlargest(7, "volume")

          date      open      high       low     close     volume ticker
142 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
53  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
57  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
54  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
433 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
496 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
463 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

# 2h

In [34]:
faanf_melted = pd.melt(
    faanf,
    id_vars=["date", "ticker"])

In [35]:
faanf_melted.head(10)

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000
5 2018-01-03   AAPL     open   169.2521
6 2018-01-03   AMZN     open  1188.3000
7 2018-01-03     FB     open   181.8800
8 2018-01-03   GOOG     open  1064.3100
9 2018-01-03   NFLX     open   202.0500